version: '3'
services:

  simple-app-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306

  myapp-main:
    image: simple-docker-app
    restart: on-failure
    depends_on:
      - simple-app-db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
