version: '3.9'
services:

  simple-app-db:
#    image: app_simple-app-db
    build:
      context: .
      args:
        - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  myapp-main:
#    image: simple-docker-app
    build:
      context: ..
    restart: on-failure
    depends_on:
      - simple-app-db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    volumes:
      - /home/sampath/Projects/rnd/simple-docker/app/logs:/app/logs

